### ISSUE TITLE
Store SpanContext inside context.Context

### ISSUE THREAD

**Issue by bg451** [opentracing/opentracing-go#105]
`StartSpanFromContext` tries to extract a Span from the context and use its SpanContext to start a new span. Now that `SpanContext`s are implemented, I think it would make more sense to store the `SpanContext` inside of the `context.Context` instead of the live `Span`. Same thing applies for `ContextWithSpan` and `SpanFromContext`.

/cc @yurishkuro @bensigelman

**Comment by bg451** [comment]
Also I think there was an intention to do this, since the comment for `ContextWithSpan` mentions it: https://github.com/opentracing/opentracing-go/blob/master/gocontext.go#L10

**Comment by yurishkuro** [comment]
I've had many situations where span is created and added to the context at one level, but more data added to the span in the nested functions. So it's not enough to have just the SpanContext in the Go Context.
