### ISSUE TITLE
nextMockID is flawed

### ISSUE THREAD

**Issue by toffaletti** [opentracing/opentracing-go#107]
As written using atomic add then load, it isn't guaranteed to return unique values. There is a race where multiple adds could happen before load causing the loads to all return the same value. Luckily there is an easy fix, atomic add returns the new value so just get rid of the load and return the value from atomic add.

**Comment by bensigelman** [comment]
@toffaletti thanks for documenting this -- would you be willing to put together the (short) PR to address the issue?
