### ISSUE TITLE
Goroutine safety guarantees

### ISSUE THREAD

**Issue by slimsag** [opentracing/opentracing-go#11]
From looking at the interfaces currently; I do not see much mention of what can / cannot be called concurrently. When dealing with multiple implementations of the same interfaces, I think it is especially important to be partisans of defining what both implementations and users of these implementations should expect.

I'll have more time to look into this over the next few days, so apologies for no specific examples at this moment.

**Comment by yurishkuro** [comment]
Should we not assume all methods must be thread-safe?

**Comment by slimsag** [comment]
That sounds okay to me. But I think we should document this somewhere.

**Comment by bensigelman** [comment]
I agree that it should be documented... I'll close this when I get around to it (sadly dealing with some non-`opentracing` stuff today :).

**Comment by slimsag** [comment]
Fixed by #21
