### ISSUE TITLE
Should opentracing expose baggage prefixes used for Tracer Inject/Extract

### ISSUE THREAD

**Issue by willhug** [opentracing/opentracing-go#121]
(Using HTTP headers as the example for simplicity)
In the Tracer interface, opentracing allows SpanContexts to be Injected and Extracted in HTTP headers to pass information over the wire.  For our purposes we use a custom prefix appended to the headers to distinguish which headers are being injected by opentracing baggage (as opposed to application headers).

One issue that surfaces with including headers from opentracing and application headers is that there is a possibility that there are collisions.  Possible solutions for this would be exposing a function that either gives a list of prefixes to avoid for application headers, or a validation function for ensuring that a header does not conflict with our tracer.

What do people think?

**Comment by yurishkuro** [comment]
Alternative solutions:
  * tracer implementation can accept configuration telling it which headers to use
  * rpc framework can namespace tracing headers, e.g. by using a special prefix (we did this in TChannel)
  * tracing implementation can simply document the format of the headers it uses

**Comment by yurishkuro** [comment]
closing old issue
