### ISSUE TITLE
Apply for GSoC 2017

### ISSUE THREAD

**Issue by SecretLiang** [opentracing/opentracing-go#132]
Hi, I am master student who want to apply to GSOC 2017, and I'd like to instrument OpenTracing to go-restful (https://github.com/emicklei/go-restful), a wildly used Golang REST web services framework. I am very familiar with Golang and have several projects that involving go-restful  in the past.

I tried to query through community@opentracing.io, but unfortunately, no one response. So I open an issue here. 

Could you guys apply for GSoC 2017?

**Comment by pritianka** [comment]
Hi - I just sent you a note! Would love to know more about GSoC and how you want to be involved.

**Comment by SecretLiang** [comment]
@pritianka Just a reminder, GSoC 2017 application deadline is Feb. 9th

**Comment by SecretLiang** [comment]
And more ideas:
* instrument Opentracing with Golang "net/rpc" standard lib.
