### ISSUE TITLE
Performance benchmarking framework

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-go#137]
I think it would be interesting to have a common performance benchmarking framework (similar to the API compatibility test harness that we have in OT for Python & JS) where one can plug in a tracer implementation and observe its impact on various service metrics. Tracer implementations can always do their own benchmarks, but micro-benchmarks don't tell much about what impact tracing instrumentation will have on a real microservice. A common benchmarks could measure tracing impact on things like:
  * CPU utilization
  * service throughput and latency
  * memory pressure

**Comment by bhs** [comment]
cc @jmacd

**Comment by yurishkuro** [comment]
unlikely to be implemented given the status of the prroject
