### ISSUE TITLE
Contextually starting span if a parent exists

### ISSUE THREAD

**Issue by stephen** [opentracing/opentracing-go#143]
In our codebase, we have places where we want to start a span conditionally if there is already a parent span. i.e. certain entry points into the codepaths are traced, but not all. i.e. maybe we want to create traces from our REST API, but not our websocket API, and both call into some database fetching code that we want to trace for the former.

To this end, we end up writing a lot of code that looks like:
```golang
// ... in the db fetch method
if span := opentracing.SpanFromContext(ctx); span != nil {
  span, ctx = opentracing.StartSpanFromContext(ctx, "db.operation")
  defer span.Finish()
}

// ...

if span != nil {
  span.LogFields("value", value)
}
```

Is there a nicer way around this pattern? Having to do nil checks + the if statement gets to be tedious.

**Comment by yurishkuro** [comment]
> Having to do nil checks + the if statement gets to be tedious.

I think if your "domain" layer must deal with situations when the span may or may not be available, the nil checks are unavoidable. You could write static functions like

```go
package tracesupport

func SetTag(ctx context.Context, key string, value interface{}) {
    if span := opentracing.SpanFromContext(ctx); span != nil {
        span.SetTag(key, value)
    }
}
```

and use these to instrument your domain layer.

Another alternative is to ensure there is always _some_ span in the context before calling into the domain layer, e.g. a Noop span from the web socket handler. The problem with that is if you later call `tracer.Inject()` and pass Noop span context, the tracer might blow up, as it has not been a requirement in the OT API for tracers to handle foreign spans gracefully.

**Comment by stephen** [comment]
That's what I figured. I wanted to double check that there wasn't something I overlooked. I think passing a no-op span makes sense, though a nicer pattern might be a `MaybeStartSpanFromContext` that returns a no-op span:
```
span, ctx := opentracing.MaybeStartSpanFromContext(ctx, "operation") // returns real Span or a StubSpan
defer span.Finish()
// ...
span.LogFields("value", value)
```
but doesn't contribute itself to the context so that downstream `StartSpanFromContext` / `SpanFromContext` (and `Inject` implicitly) still does the right thing.

This feels like a useful addition that could be in the domain of what this library provides.

**Comment by bhs** [comment]
> In our codebase, we have places where we want to start a span conditionally if there is already a parent span. i.e. certain entry points into the codepaths are traced, but not all. i.e. maybe we want to create traces from our REST API, but not our websocket API, and both call into some database fetching code that we want to trace for the former.

@stephen I'm confused about this use case... in general, I think it's (kinda) bad news to condition Span instrumentation on the presence or absence of a parent Span. That is essentially a sampling decision, and IMO it's best left to the Tracer implementation. Is there a way to solve this problem at that layer? Perhaps even through an adapter? It almost sounds like you only want to create "real" Spans when you're either (a) at process ingress in a web handler, or (b) directly descending from a "real" Span. That logic could all be confined to the Tracer implementation IIUC. Hope this helps...

**Comment by stephen** [comment]
@bhs 
> It almost sounds like you only want to create "real" Spans when you're either (a) at process ingress in a web handler, or (b) directly descending from a "real" Span.

Yes, this is more or less what we want. It sounds like you're suggesting extending the `opentracing.Tracer` (we're using `zipkin-go-opentracing`'s), but I've found it difficult to do from just "overriding" the `StartSpan` function.

I've been trying out passing back a `MockSpan` that looks like
```golang
// initialized with
// span, _ := opentracing.StartSpanFromContext(ctx, operationName, opts...)
// return &MockSpan{Span: span}, ctx
type MockSpan struct {
	opentracing.Span
}

func (m *MockSpan) FinishWithOptions(opts opentracing.FinishOptions) {}
```
I've found that with this approach, the `MockSpan` will still get contributed to the trace if some downstream child span of `MockSpan` is a plain old zipkin span. This would happen from just overriding `StartSpan`, since it has no control over `StartSpanFromContext`'s behavior. This seems like a hack, so I'd welcome suggestions for how to avoid this.

> That is essentially a sampling decision, and IMO it's best left to the Tracer implementation. 

Could you discuss more about why this is true? This makes sense to me for deciding whether or not to sample a root span, but not for sub-operations. Here's some code to make my original use case more clear. 

```golang
// websocket api
ws.HandleFunc(func (socket *Socket) {
  // i want this to be a root trace
  span, ctx := opentracing.StartSpanFromContext(ctx)
  defer span.Finish()
  // ...
  data := fetchFromDb(...)
});

// rest api
router.HandleFunc("/some-endpoint", func (w http.ResponseWriter, r *http.Request) {
  // i don't want any traces for this endpoint, or any sub operations
  data := fetchFromDb(...)
});

func fetchFromDb() ... {
  // i want this to show up in traces for the websocket, but never as a new top-level span.
  span, ctx := MaybeStartSpanFromContext(ctx)
  // ...
}
```

**Comment by bhs** [comment]
Sorry for the long delay on my part.

@stephen in my view, sampling should be a global decision; or at least it *cannot* be a local decision since sampling affects subtrees/subgraphs which will not necessarily *be* local.

What you *want* is very reasonable. My argument is that it's not an instrumentation concern. `/some-endpoint` in your example still can have a Span, it's just not a Span you personally want to spend time thinking about from an analytical standpoint. A tracing system *could* be configured to weight sampling towards or away from certain Spans or even tags, and that's why I think it's a Tracer concern. Ideally the instrumentation just describes literally what's happening and does not try to make assessments about what's "interesting" since that literally changes from human to human and month to month.

**Comment by yurishkuro** [comment]
closing old issue
