### ISSUE TITLE
GlobalTracer() should panic before SetGlobalTracer 

### ISSUE THREAD

**Issue by omeid** [opentracing/opentracing-go#151]
> Before `SetGlobalTracer()` is called, the `GlobalTracer()` is a noop implementation that drops all data handed to it.

Why?

I believe it is best if `GlobalTrace()` paniced when called before `SetGlobalTracer` or at least printed out the tracers to standard output instead of silently sending traces to a blackhole.

Happy to create a pull request to fix this up.

**Comment by yurishkuro** [comment]
No interest in this. It's not a good practice to panic in observability libraries.
