### ISSUE TITLE
Why not use "context"

### ISSUE THREAD

**Issue by cloudaice** [opentracing/opentracing-go#153]
Why not use "context" instead of "golang.org/x/net/context" ?

**Comment by yurishkuro** [comment]
We are still keeping 1.6 compatibility

**Comment by tonyghita** [comment]
Now that 1.9 is released, are we still targeting go 1.6 compat?

**Comment by yurishkuro** [comment]
My preference is to drop 1.6 support (#147)

**Comment by tonyghita** [comment]
I've opened #176 to resolve this issue.
