### ISSUE TITLE
Shall we change peer.ipv4 to String tag in golang impl?

### ISSUE THREAD

**Issue by NeoCN** [opentracing/opentracing-go#154]
I noticed that `peer.ipv4` tag defined in `ext` package is uint32 type
```golang
// PeerHostIPv4 records IP v4 host address of the peer
PeerHostIPv4 = uint32TagName("peer.ipv4")
```
but , according to [Standard Span tags and log fields](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table), the `peer.ipv4` tag is described as 

-- | -- | --
:--: | :--: | :-- 
peer.ipv4 | string | Remote IPv4 address as a .-separated tuple. E.g., "127.0.0.1"
-- | -- | --

So, follow the conventions or keep the current code?

**Comment by yurishkuro** [comment]
we should not change the existing tag, it will be a breaking change that requires a new major version. We can add something like `PeerHostIPv4Str` with the same `peer.ipv4` key but as a string tag, and add comments to `PeerHostIPv4` to explain the reasoning. 

@NeoCN are you ok to do a pull request?

**Comment by NeoCN** [comment]
@yurishkuro done!
