### ISSUE TITLE
Race conditions in spanImpl

### ISSUE THREAD

**Issue by andy-kimball** [opentracing/opentracing-go#163]
The `Context` method of `spanImpl` does not take a lock:

```
func (s *spanImpl) Context() opentracing.SpanContext {
	return s.raw.Context
}
```

Therefore, another thread could be trying to set a baggage item at the same time, and cause a race:

```
	s.Lock()
	defer s.Unlock()
	s.raw.Context = s.raw.Context.WithBaggageItem(key, val)
	return s
```

Furthermore, the `Context` method is currently causing a new object to be created every time it's called, because it's returning `s.raw.Context` rather than `&s.raw.Context` (was that deliberate? if so, there should be a comment, because it's not obvious what's going on). Unfortunately, "fixing" this to use the address could trigger new race conditions, since now `ForeachBaggageItem` will be racing with `SetBaggageItem`.

There is another race condition with the `Operation` method, which isn't using a lock to access `s.raw.Operation`. It will race with `SetOperation`.

It seems that all these issues could have been avoided by making spans immutable after construction (but probably not possible to do at this point).

**Comment by yurishkuro** [comment]
I think this was fixed by #170
