### ISSUE TITLE
error.object or just error?

### ISSUE THREAD

**Issue by kr** [opentracing/opentracing-go#164]
https://github.com/opentracing/specification/blob/master/semantic_conventions.md says to use `"error.object"` as the log key for an error object, but https://github.com/opentracing/opentracing-go/blob/1361b9cd60be79c4c3a7fa9841b3c132e40066a7/log/field.go#L126-L132 uses `"error"`. Which is right?

**Comment by yurishkuro** [comment]
I think `error.object` would've been the right name in opentracing-go/log/field.go

**Comment by miry** [comment]
@yurishkuro Is any reason to not merge #179 to fix this issue ?
