### ISSUE TITLE
Provide an example of use with plain `context.Context`?

### ISSUE THREAD

**Issue by sayden** [opentracing/opentracing-go#166]
I'm trying to use opentracing with Google PubSub golang's client. While I can successfully use it with HTTP requests and gRPC using respective wrappers, I have spent the last 4-5 hours trying to implement this simple thing using the context you pass to the `Publish` operation in Google PubSub.

In general terms, it would be nice to have an example of how to use this with services that simply accepts a `context.Context`.

**Comment by savaki** [comment]
Are you looking for something beyond

```
span, ctx := opentracing.StartSpanFromContext(ctx, "operationName")
defer span.Finish()
```

ctx in the above is just a plain old context.Context

**Comment by yurishkuro** [comment]
I'm assuming this was answered, closing.
