### ISSUE TITLE
Rename ext package to tag

### ISSUE THREAD

**Issue by gbbr** [opentracing/opentracing-go#171]
As the title suggests, in Go, the package name can be considered part of the identifier, so `tag.Error` makes a lot more sense than `ext.Error`, which doesn't mean much. 

The package holds a set of _tags_.  I would like to suggest renaming it as such.

To encourage OpenTracing adoption, it's best we stick to the language idioms and conventions.

**Comment by yurishkuro** [comment]
Duplicate of #92

**Comment by gbbr** [comment]
@yurishkuro Note that I was suggesting “tag”, not “tags”. It sounds better in singular when in use (e.g. “tag.Error” vs “tags.Error”). It is quite common in Go to use singular.

**Comment by yurishkuro** [comment]
Yeah, I'd be fine with `tag` (matches the `log` pkg)
