### ISSUE TITLE
Tracing spans across boundaries (e.g. pubsub)

### ISSUE THREAD

**Issue by mvpmvh** [opentracing/opentracing-go#185]
## Use Case
I have 2 services and a message bus. Service-A publishes a message to the bus and Service-B consumes from the bus. I would like to trace spans from Service-A to Service-B. After reading the docs, it seems to me that Service-A should start a span with tags that include `message_bus.destination` and `producer` and Service-B should have tag `consumer`. Where I get lost is how to use `FollowsFrom`. I assume that somehow, Service-B is supposed start a span that "FollowsFrom" the span context of Service-A. How do I get the `SpanContext` from Service-A to be serialized and published to the bus and deserialized once the message arrives to Service-B? 

## Problem
Trying to serialize the `SpanContext` in Service-A fails because a `SpanContext` is an interface. I would need to register a concrete implementation in order to serialize/deserialize it. Is this even the correct approach?

**Comment by yurishkuro** [comment]
Serialization is handled by the Tracer instance, `tracer.Inject(spanContext, format, carrier)`, no different from how it's done for HTTP requests.

**Comment by yurishkuro** [comment]
Working example (in Java) of tracing through Kafka: https://github.com/PacktPublishing/Mastering-Distributed-Tracing/tree/master/Chapter05
