### ISSUE TITLE
Possible to set the format of SpanIDand traceID? 

### ISSUE THREAD

**Issue by etsangsplk** [opentracing/opentracing-go#190]
## Use Case
Different tracing system has slightly different format for SpanID or traceID. But payload structure are mostly the same. So is it possible to create SPanId and traceID just like start or end time? E.g pass in  some callback to generate PsId?
Please explain your user story, what you are trying to do, which problem you are trying to .

## Problem
What prevents you from solving your use case.

## Proposal
A proposal that from your POV would solve the problem or improve the existing situation. If you don't have a proposed 
solution, that's fine too.

## Questions to address (if any)
Questions that should be answered during the discussion of this issue before
jumping into code.

**Comment by yurishkuro** [comment]
what do you mean by "format"? How it is serialized on the wire?

**Comment by etsangsplk** [comment]
Yes.  For example aws-xray has a different wire format for SpanId. 
Since I need to use their backend for the moment but want to keep to the standard open tracing API. I am investigating if there is a easier to potentially pass through what generated from opentracing and can get those recognised by aws-xray

**Comment by yurishkuro** [comment]
OpenTracing is just an API, it does not dictate how people who implement it choose to serialize span context. That is the whole point of being vendor neutral API. It is already implemented by different vendors who have vastly different ways to represent span context. The x-ray SDK can also implement OpenTracing.
