### ISSUE TITLE
Proposal: allow Tracers to override StartSpanFromContext behaviour

### ISSUE THREAD

**Issue by axw** [opentracing/opentracing-go#192]
## Use Case

I am the developer of [Elastic APM's Go agent](https://github.com/elastic/apm-agent-go). We have recently been working on an implementation of the OpenTracing API built atop our core API: https://github.com/elastic/apm-agent-go/tree/v2/module/apmot.

What is there works, but is not ideal. We have our own instrumentation modules which are tailored and optimised for our data model, minimising overhead, and its scope is wider than distributed tracing.

Ideally we would also be able to mix the tracing events created via either our native API or the OpenTracing API transparently. For example, using our native API, one would typically do something like this:

```
ctx := context.Background()
apmTransaction := elasticapm.DefaultTracer.StartTransaction("name", "type")
ctx = elasticapm.ContextWithTransaction(ctx, apmTransaction)
apmSpan, ctx := elasticapm.StartSpan(ctx, "name", "type")
```

If you use the "module/apmot" OpenTracing bridge, ideally you could then do this:

```
otSpan, ctx := opentracing.StartSpanFromContext(ctx, "name")
```

... and have resulting span be a child of "apmSpan" above. This would give our users the option of instrumenting their code with the OpenTracing API and have the events correlated with the instrumentation modules we provide.

## Problem

The StartSpanFromContext API will use a Span from the given context as the parent, but this assumes you've used OpenTracing to create the parent. This currently does not work because our native API does not deal with OpenTracing spans, and changing it to do so would cause unacceptable overhead due to additional object allocations.

## Proposal

I would like to propose an extension to StartSpanFromContext, allowing Tracers to implement an optional interface to override the behaviour. This would enable tracers to obtain/synthesise SpanContext in some alternative manner. Concretely, something like this:

```
diff --git a/gocontext.go b/gocontext.go
index 05a62e7..bb5ad11 100644
--- a/gocontext.go
+++ b/gocontext.go
@@ -41,7 +41,14 @@ func SpanFromContext(ctx context.Context) Span {
 //        ...
 //    }
 func StartSpanFromContext(ctx context.Context, operationName string, opts ...StartSpanOption) (Span, context.Context) {
-       return startSpanFromContextWithTracer(ctx, GlobalTracer(), operationName, opts...)
+       type fromContext interface {
+               StartSpanFromContext(ctx context.Context, operationName string, opts ...StartSpanOption) (Span, context.Context)
+       }
+       t := GlobalTracer()
+       if t, ok := t.(fromContext); ok {
+               return t.StartSpanFromContext(ctx, operationName, opts...)
+       }
+       return startSpanFromContextWithTracer(ctx, t, operationName, opts...)
 }
```

If this is acceptable, I would be happy to send a pull request with the changes and work them through.

**Comment by axw** [comment]
> Does it really solve your problem though? The static helper method is just that, a helper. It's perfectly legal in OT to do the same thing directly, ie get SpanFromContext and use it as parent, in which case the cast from elastic span will fail, as I understand.

The issue is not due to casting; our native objects are stored in the context independently from the OT spans, so SpanFromContext would never return our native objects. The issue is that the parent trace context is stored in the context in something that OpenTracing doesn't know about.

To be clear, I have prototyped this and it works ([gory details](https://github.com/axw/apm-agent-go/commit/c32aba5c73494078f7e9701493a67b23ab1bc39a)). I'll explain a bit more about how I would use it. Our Tracer implementation would implement StartSpanFromContext roughly like:

 1. check if there's an OT span in ctx, if there is, use that
 2. otherwise check if there's an Elastic transaction or span in ctx, if there is, extract the trace context out of it and synthesise a SpanContext object from them on the fly

Having said all that, your comment about StartSpanFromContext being just a helper got me thinking some more. Overriding its behaviour wouldn't be sufficient, as it doesn't cover the pattern

```
if parent := opentracing.SpanFromContext(ctx); parent != nil {
    span, ctx := opentracing.StartSpan(name, opentracing.ChildOf(parent))
    ...
}
```

So really, it's the behaviour of opentracing.SpanFromContext that we would need to adjust, in a similar sort of way (i.e. delegating to a hypothetical Tracer.SpanFromContext method.)

> Could you elaborate why elastic span cannot just implement OpenTracing span? Method clashes?

Yes, method clashes, but also:

- consistency with our other language clients. They could do the same, but their use is more established
- nomenclature clashes. We also have a concept of transactions (~incoming requests) which fit into OT spans. This _might_ change in the future, but for now there's a bit of disparity, and it would be confusing to our users to mix the terms without a clear delineation such as the different packages.
- performance reasons. We have made the conscious decision in our API to disallow reference to a transaction or span after it has been ended, which enables object pooling. OT's spans can be referenced after they're finished for the purpose of obtaining a SpanContext, which does not permit pooling.

**Comment by axw** [comment]
A little more background:

The Elastic APM Java agent also implements the OpenTracing API. It is able to automatically correlate with the native transactions/spans because it implements a ScopeManager. To obtain equivalent behaviour in the Go API, I think opentracing.SpanFromContext and opentracing.ContextWithSpan would need to consult the global tracer.

**Comment by axw** [comment]
> Global tracer does not receive the context itself so it will be impossible
to determine what to extract from context. I think the problem here is that
you are using a bridge as opposed to use a native implementation.
>
> OT, in the way it is conceived, requires that all your instrumentation uses
the OpenTracing interfaces within the same application.
> 
> What you require might not be possible because it will require the tracer
to accept a context which adds a surface over the API.

Right, this is the current state of affairs. My question is: can this be changed? Why require such a tight coupling?

As an alternative to my original proposal, we could do this:

1. Introduce a new interface which Tracer can optionally implement (name is a placeholder):

```go
type TracerContext interface {
    ContextWithSpan(context.Context, Span) context.Context
    SpanFromContext(context.Context) Span
}
```

2. change opentracing.ContextFromSpan like to check if the span's tracer implements TracerContext, and use that instead of calling context.WithValue directly:

```go
func ContextWithSpan(ctx context.Context, span Span) context.Context {
    if tc, ok := span.Tracer().(TracerContext); ok {
        return tc.ContextWithSpan(ctx, span)
    }
    return context.WithValue(ctx, activeSpanKey, span)
}
```

3. change SpanFromContext to first check if the context contains a value using `context.Value`, and if it doesn't, check if the global tracer implements TracerContext and calls its SpanFromContext method:

```go
func SpanFromContext(ctx context.Context) Span {
    val := ctx.Value(activeSpanKey)
    if sp, ok := val.(Span); ok {
        return sp
    }
    if tc, ok := GlobalTracer().(TracerContext); ok {
        return tc.SpanFromContext(ctx)
    }
    return nil
}
```

**Comment by jcchavezs** [comment]
I totally understand your problem @axw. In the way I see this, we could do something like:

```go
type ContextPropagator interface {
    func Extract (context.Context) Span
    func Inject (context.Context, Span) context.Context
}

type StdContextPropagator struct {}
func (scp *StdContextPropagator) Extract (context.Context) Span {
...
}

func (scp *StdContextPropagator) Inject (context.Context, Span) context.Context {
...
}

var defaultContextPropagator StdContextPropagator

func SpanFromContext(ctx context.Context) Span {
    return defaultContextPropagator.Extract(ctx)
}

func ContextWithSpan(ctx context.Context, span Span) context.Context {
   return defaultContextPropagator.Inject(ctx, span)
}
```

However I am not too optimistic this could be part of the standard library as this issue is related to not using OT instrumentation.

**Comment by axw** [comment]
@jcchavezs that looks better. More explicit, and in line with how GlobalTracer works.

**Comment by axw** [comment]
I came up with a solution in the Elastic APM OT implementation (https://github.com/elastic/apm-agent-go/pull/235); not perfect, but works well enough. This issue is clearly not going anywhere, so I'll close it.
