### ISSUE TITLE
time for a new release?

### ISSUE THREAD

**Issue by Dieterbe** [opentracing/opentracing-go#198]
Last release was 1.5 years ago.
meanwhile, useful stuff has landed in master: https://github.com/opentracing/opentracing-go/compare/v1.0.2...master
in particular #159 looks quite useful.
I notice jaeger-client-go points to the latest opentracing-go release, so it doesn't leverage changes that are in master but not in an official release.
my concern is thus that my application using jaeger-client-go may have bugs for which fixes exist but can't use yet because of the pinning to the latest release.

thank you.

**Comment by yurishkuro** [comment]
Looks like the most significant change is replacing x/net/Context with official Context.

I wonder if we should do a major release instead. But then we probably have some pending API cleanup tasks.

**Comment by yurishkuro** [comment]
https://github.com/opentracing/opentracing-go/releases/tag/v1.1.0
