### ISSUE TITLE
TraceID from span using FollowsFrom

### ISSUE THREAD

**Issue by willyyang** [opentracing/opentracing-go#203]
If a span is created as the following 
```
spanB = opentracing.StartSpan("resourceName", opentracing.FollowsFrom(spanAContext))
```
should spanB and spanA have the same traceID?

**Comment by yurishkuro** [comment]
I don't think it's explicitly documented / required by the spec, but it's the default behavior of most implementations. I think there was allowance for the tracers to decide to start a new trace if span A is "old enough".

**Comment by willyyang** [comment]
Can you explain what you mean by "old enough"? I'm seeing that the span created using `FollowsFrom` does not have the same traceID as the one it's following from.

**Comment by yurishkuro** [comment]
"old enough" - say over n minutes long. Like I said, it was theoretical and I don't know any tracers that actually implement that.

Re You specific issue - which implementation are you using? You should open a ticket in that repo.
