### ISSUE TITLE
que: add custom logger, into my http middlewares

### ISSUE THREAD

**Issue by lghinet** [opentracing/opentracing-go#212]
hello ,
any idea how can i create a custom logger, which saves logs into
the active span, if any opentracing middleware is active, or just log to
logrus or zerolog if not.

in my code i just want to use log.error(err), and log into the current span
created by a previous middleware, and into the console

in c#, you can have many logProviders , and with an tracerAccessor
you can get de current active span, and log
https://github.com/opentracing-contrib/csharp-netcore/blob/master/src/OpenTracing.Contrib.NetCore/Logging/OpenTracingLogger.cs

**Comment by lghinet** [comment]
i tried with logger hooks, but i cant get the request context in there,  to use as argument to opentracing.SpanFromContext

**Comment by yurishkuro** [comment]
@lghinet in Go you cannot use normal logging APIs without some tricks.

Example: https://github.com/jaegertracing/jaeger/tree/master/examples/hotrod/pkg/log

**Comment by lghinet** [comment]
so i have to use logger.For(ctx).Info(....)
i was hopping for logger.Info()... and then some sort of context accessor, to get the active span

**Comment by lghinet** [comment]
and then if this is the way to do it, how should i pass the logger factory, through all my middlewares? using context ?

**Comment by lghinet** [comment]
thanks
