### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by Steiniche** [opentracing/opentracing-go#225]
##  Use Case
https://github.com/opentracing/opentracing-go/issues/92 has the tag Help Wanted.
I and others want to help you solve such issues.

## Problem
There is currently no contributing guide (CONTRIBUTING.md, example: https://github.com/prometheus/prometheus/blob/master/CONTRIBUTING.md) which makes it hard to know how this repository accepts contributions, what steps to perform and so on.

## Proposal
It would be beneficial to have a contributing guide in this repository to explain what steps need to be taken to contribute to the project, what issues not project maintainers should consider helping with and so on.

## Questions to address (if any)
- Should this repository have a contributing guide?
- What sections should it contain?

**Comment by yurishkuro** [comment]
This repository is being sunset in favor of OpenTelemetry. It's not worth the effort to write a contributing guide.
