### ISSUE TITLE
Change SetTag helpers in ext to public

### ISSUE THREAD

**Issue by blakewedwards** [opentracing/opentracing-go#228]
https://github.com/opentracing/opentracing-go/blob/a7454ce5950e83caac9774ef32cc8979e5975f30/ext/tags.go#L166

Would it be accepted to make the SetTag helpers like stringTagName public so that users of the package can make their own reusable taggers?

### Proposal

ext.stringTagName -> ext.StringTagName
ext.uint16TagName -> ext.Uint16TagName
etc.

**Comment by yurishkuro** [comment]
I think it'd make sense. The current private types are a bit weird - we return private type, but expect users to use a public method on it. And those methods don't show in godocs

https://godoc.org/github.com/opentracing/opentracing-go/ext

**Comment by blakewedwards** [comment]
#229
