### ISSUE TITLE
Cut a final release?

### ISSUE THREAD

**Issue by lizthegrey** [opentracing/opentracing-go#233]
With OpenTracing being sunset, but compatibility libraries such as those in opentelemetry-go depending upon the OpenTracing API for our bridges, it would be helpful to cut one last release marking the APIs deprecated and allowing otel-go to depend upon a LTS version instead of a git hash past the most recent v1.1.1 release...

**Comment by yurishkuro** [comment]
Cut a new release (long overdue) https://github.com/opentracing/opentracing-go/releases/tag/v1.2.0

Don't think we're ready to mark it deprecated (not to mention that doing it literally with Deprecated comment would break some linters like staticcheck).

**Comment by lizthegrey** [comment]
Great, thank you! I'll get otel-go updated.
