### ISSUE TITLE
Parent context cancelation gives gRPC client error

### ISSUE THREAD

**Issue by luisfmelo** [opentracing/opentracing-go#238]
Hello guys, I searched and did not find any duplicate. If for some reason my search was a poor one, I apologize! 

If you can help me I would be very appreciated. Hope the schematic is understandable. I can make some image to show what I intend.

## Use Case
I have an echo API. In my controller, after the creation of a resource, I have a go function to make audit (via gRPC).
I want to have visibility like this:

HTTP server.............-------------------------------------------------..............................................
HTTP controller...........-------------------------------------------....................................................
gRPC client...............................................................................-----------------------...................
gRPC Server.................................................................................--------------...........................

## Problem
I'm integrating jaeger and it requires the parent context (HTTP controller).
The issue is that it all functions well except for the jaeger tracing because the context of the HTTP request is cancelled (the request ends) and in jaeger, I see that as an error (in the gRPC client)

## Questions to address (if any)
Is there any way to keep the context alive while there are go functions running? Or at least create a new childSpan without using the context itself?

**Comment by yurishkuro** [comment]
Sorry, I don't understand the issue you're having. Context is used as a mechanism to pass Span between functions. It works whether the context is cancelled or not. And to start child spans you do *not* need Context, you only need the parent span.

**Comment by luisfmelo** [comment]
I have something like this:

controller.go
```go
func Controller(c echo.Context) error {
	...
	go audit(c echo.Context)
	return nil
}
```

audit.go 
```go
func audit(c echo.Context, event *proto.Event)
	ctx := c.Get(OTContext).(context.Context)
	
	_, err := grpcClient.AuditLogCreate(ctx, event)
	if err != nil {
		panic("error")
	}

	grpcClient.Close()
```

Note: I added the unary interceptors in `github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc`.

*So what happens is *

- the grpc client call is spawned but ends up quickly with an error: `rpc error: code = Canceled desc = context canceled`

- the grpc server is sometimes spawned and sometimes not spawned. But, when it is spawned, everything seems to be fine.

**Comment by yurishkuro** [comment]
So Controller is an RPC server, but you're trying to do something else in the background? In this case you need to create a new Context for the background activity that is independent of the main RPC context, because the cancellations will screw up your background RPCs. In order to keep the trace intact, you need to copy the Span from the RPC context into background context, using `opentracing.SpanFromContext` and `ContextWithSpan`, something like this (I will use official Context):
```
func Controller(c echo.Context) error {
	...
       ctx := opentracing.ContextWithSpan(context.Background(), opentracing.SpanFromContext(c))
       // set new Deadline if you need it
	go audit(ctx)
	return nil
}
```

**Comment by luisfmelo** [comment]
Thanks. It was exactly what I needed.
