### ISSUE TITLE
TraceContext.SetAttribute has undefined behavior

### ISSUE THREAD

**Issue by slimsag** [opentracing/opentracing-go#27]
[See here](https://github.com/opentracing/api-golang/blob/master/opentracing/tracecontext.go#L51-L53)

This seems pretty bad IMO. I think we should be clear about the behavior. Imagine all the different behaviors for implementations:

- Panics on an invalid key.
- No-op on an invalid key.
- Use canonicalized form of invalid key.

Switching between tracing systems would be pretty rough if the behavior changes between them!

**Comment by bensigelman** [comment]
"Undefined behavior" means "don't do this". I believe fairly firmly that production monitoring software should never panic unless there is evidence of internal corruption (and even then I'd hesitate), yet debug monitoring software might very well do so. Given that implementations can run the gamut from production to dev and everything in between, it's hard to know what to suggest here... Do you have a particular remedy in mind?

**Comment by slimsag** [comment]
As a user of this library, that is my primary concern. Does "Undefined behavior" and "don't do this" mean that my app will panic if I accidently pass in an invalid key? I have no clue, and now I'm left to check the implementations behavior. I agree that a panic is not good for this, and that is actually my reason for raising this issue. We have the opportunity to specify the behavior clearly here.

I have a preference towards automatically using the canonicalized form of an invalid key. Would you see any issues in doing so?

**Comment by yurishkuro** [comment]
forcing normalization of keys imposes performance hit on everyone, including the majority of uses who would only send valid keys. The way I would approach it is to have a dev mode in the tracing system, which enables validation and/or forced normalization of the keys via a plugin. In prod mode the tracing system would be configured not to validate/normalize the key, which makes "behavior undefined" an accurate description.

**Comment by bensigelman** [comment]
@slimslag, I'd point out that there are plenty of totally ubiquitous APIs (e.g., libc) that have lots of undefined behavior. I see it more as a common side-effect of diverse implementations than as a "problem"... I'll admit that I don't feel strongly about this, though, and am happy to go with whatever you and @yurishkuro converge on.

**Comment by slimsag** [comment]
@yurishkuro This wouldn't really be a performance hit (at least for Go..) because implementations don't need to do anything different at all, it would just be a doc change. The `net/http` package is already canonicalizing header keys for us, see e.g.

- https://gotools.org/net/http#header-go-L21-L32
- https://gotools.org/net/textproto#reader-go-L544-L569

**Comment by yurishkuro** [comment]
if I am reading textproto code correctly, it only changes capitalization, but it keeps the string intact if it sees invalid characters.

**Comment by adriancole** [comment]
I can see the point here. Ex down-casing or even validating has a cost to it. At one level, you could imagine a transport-level impl which expects valid input, or has optional validation to smoke out bugs in layers above.

If we choose to make it mandatory to drop keys, there's really nothing implementation-specific about it, except that the cost of validation is now mandatory. That said, this particular pattern is relatively cheap (esp if down-cased). It is slightly more expensive to raise vs drop, and there's additional interop costs, as we need to then talk about error classifications. Ex. in java libraries I've worked in, IllegalArgumentException is valid for things in the control of the caller. Ex. if they mistakenly put in mixed case, then they should get an exception (if that's the contract). In any case there's nothing preventing "nice" decorators which allow folks to deal with bad input. Ex. we have lenient json and html parsers.. it could be like that.

Regardless of what we do, I think the best way to come to closure on this is to think about how an interop test would behave. Not testing (aka undefined) is a choice.

**Comment by adriancole** [comment]
PS nothing stopping us from using should vs must if we want folks to pass valid input, but don't want to require implementations to validate. Ex those writing frameworks can achieve validity by using constant keys which are known to be in proper case etc, and in such case validation is an unnecessary cost.

**Comment by slimsag** [comment]
@yurishkuro Ah, dang, I completely missed that. sorry :disappointed: -- I should have double checked before stating that.

My original motivation for proposing that we define the behavior was that most implementations would already normalizing the key (via `net/http`, which I was wrong about) or checking the validity explicitly via `CanonicalizeTraceAttributeKey` and becoming no-op, and thus making this behavior defined wouldn't be a perf hit.

Given I was wrong about `net/http`, and I can certainly see the danger in requiring validation in terms of potential perf issues, I see more of the motivation for making this behavior undefined. I'll continue thinking about it as we migrate into real implementations of this API in different languages to see what common practice ends up being before sinking more time. can close this issue / punt on this for now unless anyone else objects.
