### ISSUE TITLE
API compatibility

### ISSUE THREAD

**Issue by slimsag** [opentracing/opentracing-go#35]
Hey all,

Before 1.0 is released I wanted to bring up the topic of API compatibility (even if it's already been discussed before) specifically for the Go API with the direct intent of defining our _plan_.

A few options I see:

1. Leave the package as-is, and declare that no backwards incompatible changes can ever be made to this repo. Future backwards-incompat changes will be made in opentracing/opentracing2-go or similiar.
2. Declare that "mild" backwards incompatible changes may be made and users must update their code (In practice, I've seen this as the most common including golang.org/x/ repos).
3. Use a versioning service like gopkg.in
4. Place a subdirectory for new versions, me and @shurcooL did this for example in https://github.com/go-gl/glfw so the import path is `github.com/opentracing/opentracing-go/v1/opentracing` for each version.

To be absolutely clear: I **do not care which one we go with**, but I do want us to acknowledge that _there will be backwards incompat changes at some point_.

The goal of raising this issue is only to define how we intend to handle these changes, and stick to it in the future. I have found with personal projects that being finicky and changing around is the worst strategy here, so I don't want us to fall into that and punt on choosing a strategy until we run into issues.

**Comment by bensigelman** [comment]
Thanks for raising this. I'd vote for your second option ("mild" backwards incompatibility allowed, whatever we say that means!). At one point I suggested option 4 and met resistance... can't recall whether that was over email or github or gitter or what, though!

I'm also okay with option 3, btw. I am not okay with option 1.

**Comment by yurishkuro** [comment]
+1 for #2

**Comment by shurcooL** [comment]
FWIW, I am happy with the mild API changes that golang.org/x repos make in order to improve their APIs. I prefer they do that, rather than never changing API. So option 2 would work well for me as a user.

**Comment by bensigelman** [comment]
Per https://github.com/opentracing/opentracing-go/commit/c8eb295eeceafb0871e5c8dbf83426675f75fd29, I am going to close this... hope that suffices, suggest changes if not!
