### ISSUE TITLE
Examples in Readme are out of date

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-go#60]
Would it make more sense to write a well-documented "api test" file that will demonstrate the same examples

**Comment by bensigelman** [comment]
I think we should do the godoc/test examples a la https://blog.golang.org/examples -- def better than the README alone.

**Comment by adpoint** [comment]
yurishkuro is right,examples make more sense

**Comment by msabramo** [comment]
Found this issue while searching for example code. So I agree of course.

**Comment by yurishkuro** [comment]
closing old issue
