### ISSUE TITLE
Do we want to add Tracer.Flush() ?

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-go#66]
@bensigelman @tschottdorf 

We have it in Python version.

**Comment by bensigelman** [comment]
Yes :)

Should be part of the spec, too.

**Comment by bensigelman** [comment]
(... and we could show a use-case for a shutdown handler as motivation)

**Comment by tschottdorf** [comment]
I'm neutral on that one (i.e. feel free to go ahead).

**Comment by bensigelman** [comment]
(I created https://github.com/opentracing/opentracing.github.io/issues/74 as we should really decide this once across OT in general)

**Comment by yurishkuro** [comment]
Closing, per conclusions in https://github.com/opentracing/opentracing.github.io/issues/74:

> Resolved unless new information arises: `Tracer.Flush()` (or `Close()` or similar) are the responsibility of implementations and not part of the OT API proper.
