### ISSUE TITLE
move util.go out of opentracing-go

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing-go#71]
Perhaps to basictracer-go?

**Comment by bensigelman** [comment]
(It's not part of the core OpenTracing spec/API, and we'd like to keep these repos as clean as possible)

**Comment by bg451** [comment]
How about moving it into a sub-package `/utils`? We already do something similar with ext.

**Comment by bensigelman** [comment]
NB: there's also the fact that the code adds prefixes/etc which should be handled by the carrier itself. See https://github.com/opentracing/opentracing-go/issues/29 and https://github.com/opentracing/opentracing.github.io/issues/73.

**Comment by yurishkuro** [comment]
+1 to move out. I just instrumented server/client frameworks in our internal go-common repo, and did not need to use these util methods. They look more like utils for a tracer, not the end users.

**Comment by yurishkuro** [comment]
Looks like it's been done already
