### ISSUE TITLE
TextMap carrier comments should not imply multi-map semantics

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-go#83]
```
 // TextMapWriter is the Inject() carrier for the TextMap builtin format. With
// it, the caller can encode a Span for propagation as entries in a multimap of
// unicode strings.
```

I suggest we remove the reference to multi-map, it's not reasonable to expect that all transports support multi-value headers, and tracers should not rely on that when selecting TextMap keys.

**Comment by bensigelman** [comment]
I agree... this aligns well with where the HTTP discussion ended up, too. (I.e., promoting HTTP to "required carrier" status)

**Comment by yurishkuro** [comment]
Being taken care of by #82
