### ISSUE TITLE
Move tags to `tag/` package

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-go#92]
@bensigelman - any objection to moving tags from `ext/` to `tag/`? It would make for nicer syntax `tags.PeerService.Set(...)`. Once we introduce KV logging, we could also add `logs` package, for similar syntax.

NB: we can make the change backwards compatible by defining `ext/` tags in terms of `tag/` tags.

**Comment by bensigelman** [comment]
I like the suggestion, yeah. And I am ok with breaking changes until we lock down the [OT 1.0 milestone](https://github.com/opentracing/opentracing.github.io/milestone/2).

**Comment by bensigelman** [comment]
cc @jmacd

**Comment by yurishkuro** [comment]
Was thinking more about it on the train. Strictly speaking, once we introduce KV logging, "tag" becomes a shared term between "span tags", and "log tags". But I wouldn't want to see packages `spantags` and `logtags`. Some logging frameworks use the term "fields", which feels like a made up distinction; i.e. I do like the uniformity of using the term "tags" across the board.

Thoughts on package naming?

**Comment by yurishkuro** [comment]
it's unlikely we're going to do this given the move to OpenTelemetry, closing.
