### ISSUE TITLE
MockTracer GetFinishedSpans should be merely FinishedSpans

### ISSUE THREAD

**Issue by kriskowal** [opentracing/opentracing-go#98]
Per the Go idiom of using bare names for accessors.

I’d suggest aliasing for compatibility.

**Comment by bensigelman** [comment]
Would you be willing to send a PR? I agree that the Go-ish thing would be
`FinishedSpans`. (And we have just landed some much larger breaking
changes, so one more will be a drop in the bucket -- I think it's ok not to
alias)
ᐧ

**Comment by kriskowal** [comment]
so it is written, so it shall be done. #99

**Comment by bensigelman** [comment]
@kriskowal thanks :)
